### ISSUE TITLE
phpdish:install检查writable的时候最好加上web/media

### ISSUE THREAD

**Issue by gouchaoer** [slince/phpdish#9]
放生产环境无法上传文件，发现没权限写

**Comment by slince** [comment]
嗯嗯，年后新版本发布的时候，会带上这个发自我的华为手机-------- 原始邮件 --------主题：[slince/phpdish] phpdish:install检查writable的时候最好加上web/media (#9)发件人：gouchaoer 收件人：slince/phpdish 抄送：Subscribed 放生产环境无法上传文件，发现没权限写

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/slince/phpdish","title":"slince/phpdish","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/slince/phpdish"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"phpdish:install检查writable的时候最好加上web/media (#9)"}],"action":{"name":"View Issue","url":"https://github.com/slince/phpdish/issues/9"}}}

**Comment by gouchaoer** [comment]
刚看源码里检查了的，难道我安装有问题。。。过年没事看看源码，别在意

**Comment by slince** [comment]
😂有啥好在意的
